{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "what-the-helm.serviceAccountName" . }}
  labels:
{{ include "what-the-helm.labels" . | indent 4 }}
{{- end -}}
